### ISSUE TITLE
Multiple data

### ISSUE THREAD

**Issue by Vanlen1er** [mikebski/demano#1]
Hello,

I just found your plugin and it's very good for what I need it. But I have a problem. 

I have a 3 big group with different sub-values.
It works for 2 but 1 can have 2 values like this : `data-equipement="sagex3 qualityManagement"`. So if I click on the checkbox sagex3 or qualityManagement, nothing is show.

What I would like is that if either or both are checked, the right products are displayed.

Can you help me modify your code to make it work?

Thanks

**Comment by mikebski** [comment]
@Vanlen1er - Can you create a JSfiddle or something - https://jsfiddle.net/

If you can do that I'll give it a shot - you can post the link here.

**Comment by Vanlen1er** [comment]
Thank you ! 
[https://jsfiddle.net/69kx4vfs/](url)

You can see in EQUIPEMENT that some div have two data-equipment, like the first one for example. And if you choose one of the two choices, neither will be displayed.

For the others, REGION and ACTIVITE, it works perfectly.

**Comment by Vanlen1er** [comment]
Thank you :)

I have another request, let me know if it is possible. 
Is it possible that when we choose the 2 that are in a product, we only see the product(s) that have the 2? And not all the products that have one and the other?
Thanks
